inherit_from: .rubocop_todo.yml
Metrics/LineLength:
  Max: 120
AllCops:
  Exclude:
    - 'config/initializers/devise.rb'
    - 'config/initializers/simple_form_bootstrap.rb'
    - 'config/initializers/simple_form.rb'
